language: ruby
rvm:
- 2.2.4
env:
  global:
    - V1=hi
  matrix:
    - V2=there V3=world
    - V2=is V3=working
before_install:
- echo "before_install"; echo $V1; echo $V2; echo $V3
install:
- echo "install"; echo $V1; echo $V2; echo $V3
before_script:
- echo "before_script"; echo $V1; echo $V2; echo $V3
script:
- echo "script"; echo $V1; echo $V2; echo $V3
