language: ruby # todo: checkout the selected branch and run the build system on the apps, also checkout the selected branch of the APPS_HOST
rvm:
- 2.2.4
env:
  global:
    - DB=mysql
    - TRAVIS_LAUNCHES_SAUCE_CONNECT=true # Tell the karma file that it does not need to launch Sauce connect
    - APPS_BRANCH=develop
    - APPS_REPO=https://github.com/privly/privly-applications.git # todo: change the remote to this one and pull first
    - SERVER_BRANCH=develop
    - SERVER_REPO=https://github.com/privly/privly-web.git
    - APPS_HOST_REPO=https://github.com/privly/ # The org or user account we are testing extensions and content servers on
    - RAILS_ENV=development
    - secure: "rtbxNtAkzJU+4pg5lz9lviJ0OKSjOD1bAyk+4scz5jGoXzgoG6PLbu3Zml/KCcqo9BfwaXct7ezaRd80ufN4N0wWQ9No6ldsMYQ9cZ26NeHU2Qc3pSmlJre1sAaAq9DWZWQqBDh2IpnhRdPPMghKT5RatufKkMD8wH+LgTzu0Xxlzq+47N+DLiafTUoUsMAvwocM2VDcZu3FqqOxN7DZZlfIyypKRXVtYiYjb5LCiwkSmrV/M4bBKVlE9JTY8/JiCE/CZaXyxdlp+YBPeIS8pJ62/d51Q1fC8ZcmL0gS5SeJ0bKNKY7gZEkKc0dLrk4eTilEBfE45o3pKXxq+YhOARg88v5zQgCuFwCcFulZ2cxuni3lQQ6kIck9o8KM8/aaLehW9ninjV4Y4lNHSjv/gMXTByeAlPX/J8NuYoUEvH6/b25aeHGepBNDydzVulhAkxl7Br15NePdgEBk162idHghq/bbGCLGx4k7XTVdtZP2FNKQ6GBweGR6kSu6lMle+p/mJzTEYgd28S8Toaz8hU2H88N0WB7g8NBrvwlLG231bcWL4OBPuHtIT9NkggLd0AuI+mJcK9FmxH6/kVR6ViuaDkRISNdH2yxNflVnOlv5adyeUTY5PhGQoXnDLOINQ9GbBQ1UjvkGn0BabuTdr3hjObI0IdKDriWmHP9xxOc="#SAUCE_URL="http://smcgregor:********-****-****-****-************@ondemand.saucelabs.com:80/wd/hub"(smcgregor/privly-build)
    - secure: "ifTD5r0X1H1RvC2ID9amnmbhEMGuydfGDh3YMC9PEWlntA5wdLEGanlmF9PxBaIs7lJQsvC3xujgeu2/MJXcAFyy3I5vT6o9YKoBi1ugVP8wAXcj0IMVJnYjVvuArVtkjxX8k9EpTrk6juIdlwlt4mbI9eFk5FitRzimA3Crv/6NzC6sEwJ+tljIPliIqmB7yLKZCZmxazHuWgQ3TTENORU4VmCxK9E9zVBfxQ3BMrSc/oHfFvINj2p+VYLVY3dAsNAr/xwyy7A0DKoz4A1JFDQkbA0JAwlOTEVxXbywY0EM0q3Ycs04BCjq90/xVrjrg/mRplYWGv6H7b8F6GQMK8dkR7Tkwclkcwzuo5YB8SKptW5ynk4ocomDzzHXRmG2fmD/xCngxb6CmqEmtKu63FKw8KJdmz/5W/T5T+jiqxi4IkiXwDA7+e+TKKCPmNDtAh1FT5mRosfxpL46Qmqq/WeaBiL1+ZCC5jH7wRqMdYjLrEurKdPBRNmUiQ5q9yykaI8V3teGrfDQpHeod0bOZFWQCPdgxIdb7d1AMseRJZGga8vXmPDzMs+OjamIgXjpRAMOXS1iAnq1DpjJswc48Su3vYUUqcTMGxtFflLP5BnD8xiT8z/81yVFCDPtefLb+wPE0BFAkqGN3xOfRhmzXnZoLQkMrLqa6tPjPaVzdrk="#SAUCE_USERNAME=smcgregor(smcgregor/privly-build)
  matrix:
    - APPS_HOST_NAME=privly-chrome APPS_HOST_BRANCH=develop SELENIUM_PLATFORM=sauce_chrome_extension PRIVLY_APPS_PATH=privly-applications HTML_BUILD_PLATFORM=chrome
    - APPS_HOST_NAME=privly-jetpack APPS_HOST_BRANCH=develop SELENIUM_PLATFORM=sauce_firefox_extension PRIVLY_APPS_PATH=chrome/content/privly-applications HTML_BUILD_PLATFORM=chrome
    - APPS_HOST_NAME=privly-web APPS_HOST_BRANCH=develop SELENIUM_PLATFORM=sauce_firefox_web PRIVLY_APPS_PATH=public/apps HTML_BUILD_PLATFORM=web
    - APPS_HOST_NAME=privly-web APPS_HOST_BRANCH=develop SELENIUM_PLATFORM=sauce_chrome_web PRIVLY_APPS_PATH=public/apps HTML_BUILD_PLATFORM=web
before_install: # Clone the web server
- "if [ ${APPS_HOST_NAME} != 'privly-web' ]; then git clone --recursive ${SERVER_REPO} && cd privly-web && git checkout $SERVER_BRANCH; fi" # clone the webserver if we are not testing it
install: # Install the app host
- cd $TRAVIS_BUILD_DIR
- git clone --recursive $APPS_HOST_REPO$APPS_HOST_NAME\.git # clone the extension or web server
- cd $APPS_HOST_NAME; git checkout $APPS_HOST_BRANCH
- cd $PRIVLY_APPS_PATH; git remote set-url origin $APPS_REPO; git fetch; git checkout $APPS_BRANCH
- pip install --user -r requirements.txt
- python build.py --platform=$HTML_BUILD_PLATFORM
- cd $TRAVIS_BUILD_DIR
before_script:
- cd privly-web
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database privly_test'
- bundle install #Installs the required gems
- rake db:create #Creates the Database
- rake db:schema:load #Loads the Scheme
- rake db:seed #Seeds the DB
- "bundle exec rails server -p 3000 &"
- cd $TRAVIS_BUILD_DIR;cd $APPS_HOST_NAME/$PRIVLY_APPS_PATH/test
- bundle install #Installs gems required for selenium testing
- cd selenium
script:
- "ruby run_all.rb -p $SELENIUM_PLATFORM -r experimental -c http://localhost:3000"
addons:
  sauce_connect: true
